name: docker deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2   
      - name: print work directory
        run: pwd && ls
      - name: docker build
        run: docker build -t ecomm .
      - name: run container
        run: docker container run -dt --name web -p 8080:80 ecomm
      - name: list containers
        run: docker container ls -a
