name: docker deployment
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2   
      - name: docker build
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/myecomm .
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin
      - name: push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/myecomm
      - name: remove images
        run: docker rmi ${{ vars.DOCKER_USERNAME }}/myecomm

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: remove old container container
        run: docker container rm -f web
      - name: run container
        run: docker container run -dt --name web -p 8080:80 ${{ vars.DOCKER_USERNAME }}/myecomm
      - name: list containers
        run: docker container ls -a
